"""Tests for core/crypto — CP-ABE and CKKS simulation layer."""
from __future__ import annotations

import math
import pytest
from datetime import datetime, timedelta

from core.crypto.abe import (
    ABEMasterKey, ABEPublicKey, ABEAttributeKey, Ciphertext,
    abe_setup, abe_issue_key, abe_encrypt, abe_decrypt,
    policy_satisfied, check_policy, _tokenize,
)
from core.crypto.ckks import (
    CKKSContext, CKKSEncryptedVector,
    ckks_setup, ckks_encode_encrypt, ckks_decrypt_decode,
    ckks_add, ckks_sub, ckks_multiply, ckks_inner_product,
    ckks_scale, ckks_negate, ckks_square, ckks_sum, ckks_power,
    ctx_id, ctx_id_check,
)
from core.crypto.engine import CryptoEngine, EncryptedSearchResult
from core.labels import (
    AgentLabel, MemoryLabel, Clearance, Trust, Layer, MemoryType, Role,
)
from core.topology import Topology


# ═══════════════════════════════════════════════════════════
# CP-ABE policy evaluator
# ═══════════════════════════════════════════════════════════

class TestPolicyEvaluator:
    """The policy parser is the core decision logic shared with real CP-ABE."""

    def test_single_attribute(self):
        assert policy_satisfied("role_Analyst", ["role_Analyst"])
        assert not policy_satisfied("role_Analyst", ["role_Executor"])

    def test_and(self):
        p = "clearance_2 and task_incident-1"
        assert policy_satisfied(p, ["clearance_2", "task_incident-1"])
        assert not policy_satisfied(p, ["clearance_2"])

    def test_or(self):
        p = "clearance_2 or clearance_3"
        assert policy_satisfied(p, ["clearance_2"])
        assert policy_satisfied(p, ["clearance_3"])
        assert not policy_satisfied(p, ["clearance_1"])

    def test_nested(self):
        p = "role_Planner and (clearance_2 or clearance_3)"
        assert policy_satisfied(p, ["role_Planner", "clearance_2"])
        assert policy_satisfied(p, ["role_Planner", "clearance_3"])
        assert not policy_satisfied(p, ["role_Planner", "clearance_1"])
        assert not policy_satisfied(p, ["clearance_3"])  # missing role

    def test_realistic_policy_from_labels(self):
        """Simulate a policy generated by policy_from_label()."""
        # D-layer: owner, descendants, auditor can read
        p = "agent_planner-1 or descendantof_planner-1 or role_Auditor"
        assert policy_satisfied(p, ["agent_planner-1"])
        assert policy_satisfied(p, ["descendantof_planner-1"])
        assert policy_satisfied(p, ["role_Auditor"])
        assert not policy_satisfied(p, ["agent_analyst-2"])

    def test_clearance_chain(self):
        """clearance_i is satisfied if i >= required level."""
        p = "(clearance_1 or clearance_2 or clearance_3)"
        assert policy_satisfied(p, ["clearance_2"])
        assert policy_satisfied(p, ["clearance_3"])
        assert not policy_satisfied(p, ["clearance_0"])

    def test_complex_compound(self):
        p = ("(clearance_2 or clearance_3) and task_t1 "
             "and (group_sec or group_ops) and epoch_1")
        attrs = ["clearance_2", "task_t1", "group_sec", "epoch_1"]
        assert policy_satisfied(p, attrs)

        # Missing group
        attrs_bad = ["clearance_2", "task_t1", "epoch_1"]
        assert not policy_satisfied(p, attrs_bad)

    def test_empty_policy(self):
        assert not policy_satisfied("", ["anything"])

    def test_tokenize(self):
        tokens = _tokenize("role_Analyst and (clearance_2 or clearance_3)")
        assert "role_Analyst" in tokens
        assert "and" in tokens
        assert "(" in tokens
        assert "or" in tokens
        assert ")" in tokens

    def test_check_policy_returns_reason(self):
        ok, reason = check_policy("role_Analyst", ["role_Analyst"])
        assert ok
        assert "PASS" in reason

        ok, reason = check_policy("role_Analyst", ["role_Executor"])
        assert not ok
        assert "FAIL" in reason


# ═══════════════════════════════════════════════════════════
# CP-ABE encrypt/decrypt cycle
# ═══════════════════════════════════════════════════════════

class TestABECycle:

    def test_encrypt_decrypt_allowed(self):
        mk, pk = abe_setup()
        key = abe_issue_key(mk, "agent-1", ["clearance_2", "task_t1", "role_Analyst"], epoch=1)

        ct = abe_encrypt(pk, "secret message", "clearance_2 and task_t1")
        plain = abe_decrypt(key, ct)
        assert plain is not None
        assert plain.decode() == "secret message"

    def test_encrypt_decrypt_denied_wrong_clearance(self):
        mk, pk = abe_setup()
        key = abe_issue_key(mk, "agent-1", ["clearance_1", "task_t1"], epoch=1)

        ct = abe_encrypt(pk, "classified", "clearance_2 and task_t1")
        plain = abe_decrypt(key, ct)
        assert plain is None

    def test_encrypt_decrypt_denied_wrong_task(self):
        mk, pk = abe_setup()
        key = abe_issue_key(mk, "agent-1", ["clearance_2", "task_t1"], epoch=1)

        ct = abe_encrypt(pk, "secret", "clearance_2 and task_t2")
        plain = abe_decrypt(key, ct)
        assert plain is None

    def test_encrypt_decrypt_complex_policy(self):
        mk, pk = abe_setup()
        key = abe_issue_key(mk, "planner-1", [
            "agent_planner-1", "clearance_3", "task_t1",
            "group_sec", "epoch_1", "ancestorof_analyst-1",
        ], epoch=1)

        ct = abe_encrypt(pk, "top secret plan",
                         "(clearance_2 or clearance_3) and task_t1 and group_sec and epoch_1")
        plain = abe_decrypt(key, ct)
        assert plain is not None

    def test_different_plaintexts_produce_different_ciphertexts(self):
        mk, pk = abe_setup()
        key = abe_issue_key(mk, "a1", ["clearance_3"], epoch=1)

        ct1 = abe_encrypt(pk, "message A", "clearance_3")
        ct2 = abe_encrypt(pk, "message B", "clearance_3")
        assert ct1.ct != ct2.ct

    def test_ciphertext_serialization(self):
        mk, pk = abe_setup()
        ct = abe_encrypt(pk, "test", "clearance_1")

        data = ct.to_bytes()
        ct2 = Ciphertext.from_bytes(data)
        assert ct2.policy == ct.policy

    def test_master_key_export(self):
        mk, pk = abe_setup()
        raw = mk.export()
        assert len(raw) == 32


# ═══════════════════════════════════════════════════════════
# CKKS operations
# ═══════════════════════════════════════════════════════════

class TestCKKS:

    @pytest.fixture
    def ctx(self):
        return ckks_setup()

    def test_encrypt_decrypt_roundtrip(self, ctx):
        vec = [1.0, 2.5, -3.0, 0.0, 100.0]
        enc = ckks_encode_encrypt(vec, ctx)
        dec = ckks_decrypt_decode(enc, ctx)
        for a, b in zip(vec, dec):
            assert math.isclose(a, b, rel_tol=1e-6)

    def test_add(self, ctx):
        a = ckks_encode_encrypt([1.0, 2.0, 3.0], ctx)
        b = ckks_encode_encrypt([4.0, 5.0, 6.0], ctx)
        enc_sum = ckks_add(a, b, ctx)
        dec = ckks_decrypt_decode(enc_sum, ctx)
        for x, y in zip(dec, [5.0, 7.0, 9.0]):
            assert math.isclose(x, y, rel_tol=1e-6)

    def test_sub(self, ctx):
        a = ckks_encode_encrypt([10.0, 8.0, 6.0], ctx)
        b = ckks_encode_encrypt([1.0, 2.0, 3.0], ctx)
        enc_sub = ckks_sub(a, b, ctx)
        dec = ckks_decrypt_decode(enc_sub, ctx)
        for x, y in zip(dec, [9.0, 6.0, 3.0]):
            assert math.isclose(x, y, rel_tol=1e-6)

    def test_multiply(self, ctx):
        a = ckks_encode_encrypt([2.0, 3.0, 4.0], ctx)
        b = ckks_encode_encrypt([5.0, 10.0, 0.5], ctx)
        enc_mul = ckks_multiply(a, b, ctx)
        dec = ckks_decrypt_decode(enc_mul, ctx)
        for x, y in zip(dec, [10.0, 30.0, 2.0]):
            assert math.isclose(x, y, rel_tol=1e-6)

    def test_inner_product(self, ctx):
        a = ckks_encode_encrypt([1.0, 2.0, 3.0], ctx)
        b = ckks_encode_encrypt([4.0, 5.0, 6.0], ctx)
        enc_ip = ckks_inner_product(a, b, ctx)
        dec = ckks_decrypt_decode(enc_ip, ctx)
        # 1*4 + 2*5 + 3*6 = 4+10+18 = 32
        assert math.isclose(dec[0], 32.0, rel_tol=1e-6)

    def test_scale(self, ctx):
        a = ckks_encode_encrypt([1.0, 2.0, 3.0], ctx)
        enc_scaled = ckks_scale(a, 3.0, ctx)
        dec = ckks_decrypt_decode(enc_scaled, ctx)
        for x, y in zip(dec, [3.0, 6.0, 9.0]):
            assert math.isclose(x, y, rel_tol=1e-6)

    def test_negate(self, ctx):
        a = ckks_encode_encrypt([1.0, -2.0, 3.0], ctx)
        enc_neg = ckks_negate(a, ctx)
        dec = ckks_decrypt_decode(enc_neg, ctx)
        for x, y in zip(dec, [-1.0, 2.0, -3.0]):
            assert math.isclose(x, y, rel_tol=1e-6)

    def test_square(self, ctx):
        a = ckks_encode_encrypt([1.0, 2.0, 3.0], ctx)
        enc_sq = ckks_square(a, ctx)
        dec = ckks_decrypt_decode(enc_sq, ctx)
        for x, y in zip(dec, [1.0, 4.0, 9.0]):
            assert math.isclose(x, y, rel_tol=1e-6)

    def test_sum(self, ctx):
        a = ckks_encode_encrypt([1.0, 2.0, 3.0, 4.0], ctx)
        enc_sum = ckks_sum(a, ctx)
        dec = ckks_decrypt_decode(enc_sum, ctx)
        assert math.isclose(dec[0], 10.0, rel_tol=1e-6)

    def test_power(self, ctx):
        a = ckks_encode_encrypt([1.0, 2.0, 3.0], ctx)
        enc_pow = ckks_power(a, 3, ctx)
        dec = ckks_decrypt_decode(enc_pow, ctx)
        for x, y in zip(dec, [1.0, 8.0, 27.0]):
            assert math.isclose(x, y, rel_tol=1e-6)

    def test_size_mismatch_raises(self, ctx):
        a = ckks_encode_encrypt([1.0, 2.0], ctx)
        b = ckks_encode_encrypt([1.0, 2.0, 3.0], ctx)
        with pytest.raises(ValueError):
            ckks_add(a, b, ctx)
        with pytest.raises(ValueError):
            ckks_inner_product(a, b, ctx)

    def test_context_mismatch_raises(self, ctx):
        ctx2 = ckks_setup()
        a = ckks_encode_encrypt([1.0, 2.0], ctx)
        b = ckks_encode_encrypt([1.0, 2.0], ctx2)
        with pytest.raises(ValueError):
            ckks_add(a, b, ctx)

    def test_different_encryptions_different_ciphertext(self, ctx):
        vec = [1.0, 2.0, 3.0]
        ct1 = ckks_encode_encrypt(vec, ctx)
        ct2 = ckks_encode_encrypt(vec, ctx)
        assert ct1._data != ct2._data  # probabilistic encryption

    def test_large_vector(self, ctx):
        vec = [float(i) for i in range(128)]
        enc = ckks_encode_encrypt(vec, ctx)
        dec = ckks_decrypt_decode(enc, ctx)
        for a, b in zip(vec, dec):
            assert math.isclose(a, b, rel_tol=1e-6)


# ═══════════════════════════════════════════════════════════
# CryptoEngine integration
# ═══════════════════════════════════════════════════════════

class TestCryptoEngine:

    @pytest.fixture
    def topo(self):
        t = Topology()
        t.add_agent("planner-1", parent=None)
        t.add_agent("analyst-1", parent="planner-1")
        t.add_agent("retriever-1", parent="planner-1")
        return t

    @pytest.fixture
    def engine(self, topo):
        return CryptoEngine(topo, ckks_dim=8)

    def test_register_agent(self, engine, topo):
        agent = AgentLabel(agent_id="analyst-1", role=Role.ANALYST,
                           clearance=Clearance.L2_SENSITIVE,
                           trust_intrinsic=Trust.T2_MEDIUM,
                           task_domain={"task-1"}, collab_group={"sec"},
                           epoch=1)
        key = engine.register_agent(agent)
        assert key is not None
        assert key.agent_id == "analyst-1"
        assert "clearance_2" in key.attributes
        assert "role_Analyst" in key.attributes
        assert "task_task-1" in key.attributes

    def test_encrypt_decrypt_full_cycle(self, engine, topo):
        agent = AgentLabel(agent_id="analyst-1", role=Role.ANALYST,
                           clearance=Clearance.L2_SENSITIVE,
                           trust_intrinsic=Trust.T2_MEDIUM,
                           task_domain={"task-1"}, epoch=1)
        engine.register_agent(agent)

        mem = MemoryLabel(chunk_id="m1", sensitivity=Clearance.L2_SENSITIVE,
                          provenance_trust=Trust.T3_HIGH, layer=Layer.CONCLUSION,
                          memory_type=MemoryType.INTEL, owner_agent="planner-1",
                          task_binding="task-1", epoch=1)

        ct = engine.encrypt_memory("attack ioc: 1.2.3.4", mem)
        plain, reason = engine.decrypt_memory(agent, ct)
        assert plain is not None
        assert b"1.2.3.4" in plain
        assert "ALLOW" in reason

    def test_decrypt_denied_wrong_task(self, engine, topo):
        agent = AgentLabel(agent_id="analyst-1", role=Role.ANALYST,
                           clearance=Clearance.L2_SENSITIVE,
                           trust_intrinsic=Trust.T2_MEDIUM,
                           task_domain={"other-task"}, epoch=1)
        engine.register_agent(agent)

        mem = MemoryLabel(chunk_id="m1", sensitivity=Clearance.L0_PUBLIC,
                          provenance_trust=Trust.T2_MEDIUM, layer=Layer.CONCLUSION,
                          memory_type=MemoryType.INTEL, owner_agent="planner-1",
                          task_binding="task-1", epoch=1)

        ct = engine.encrypt_memory("public info", mem)
        plain, reason = engine.decrypt_memory(agent, ct)
        assert plain is None
        assert "DENY" in reason

    def test_decrypt_denied_insufficient_clearance(self, engine, topo):
        agent = AgentLabel(agent_id="analyst-1", role=Role.ANALYST,
                           clearance=Clearance.L0_PUBLIC,  # only L0
                           trust_intrinsic=Trust.T2_MEDIUM,
                           task_domain={"task-1"}, epoch=1)
        engine.register_agent(agent)

        mem = MemoryLabel(chunk_id="m1", sensitivity=Clearance.L3_SECRET,
                          provenance_trust=Trust.T3_HIGH, layer=Layer.CONCLUSION,
                          memory_type=MemoryType.SEMANTIC, owner_agent="planner-1",
                          task_binding="task-1", epoch=1)

        ct = engine.encrypt_memory("classified", mem)
        plain, reason = engine.decrypt_memory(agent, ct)
        assert plain is None
        assert "DENY" in reason

    def test_unregistered_agent_cannot_decrypt(self, engine):
        agent = AgentLabel(agent_id="intruder", role=Role.EXTERNAL,
                           clearance=Clearance.L3_SECRET,
                           trust_intrinsic=Trust.T0_UNTRUSTED,
                           epoch=1)
        # Not registered!
        mem = MemoryLabel(chunk_id="m1", sensitivity=Clearance.L0_PUBLIC,
                          provenance_trust=Trust.T2_MEDIUM, layer=Layer.CONCLUSION,
                          memory_type=MemoryType.INTEL, owner_agent="planner-1",
                          task_binding="task-1", epoch=1)
        ct = engine.encrypt_memory("test", mem)
        plain, reason = engine.decrypt_memory(agent, ct)
        assert plain is None
        assert "未注册" in reason

    def test_stale_epoch_blocked(self, engine):
        agent = AgentLabel(agent_id="analyst-1", role=Role.ANALYST,
                           clearance=Clearance.L3_SECRET,
                           trust_intrinsic=Trust.T3_HIGH,
                           task_domain={"task-1"}, epoch=2)
        # Register with epoch=1
        key = abe_issue_key(engine.abe_mk, agent.agent_id,
                            ["clearance_3", "task_task-1", "role_Analyst", "epoch_1"],
                            epoch=1)
        engine._agent_keys[agent.agent_id] = key

        mem = MemoryLabel(chunk_id="m1", sensitivity=Clearance.L0_PUBLIC,
                          provenance_trust=Trust.T2_MEDIUM, layer=Layer.CONCLUSION,
                          memory_type=MemoryType.INTEL, owner_agent="planner-1",
                          task_binding="task-1", epoch=1)
        ct = engine.encrypt_memory("test", mem)
        plain, reason = engine.decrypt_memory(agent, ct)
        assert plain is None
        assert "epoch" in reason.lower()

    def test_revoke_agent(self, engine):
        agent = AgentLabel(agent_id="temp-1", role=Role.EXTERNAL,
                           clearance=Clearance.L1_INTERNAL,
                           trust_intrinsic=Trust.T1_LOW,
                           task_domain={"task-1"}, epoch=1)
        engine.register_agent(agent)
        engine.revoke_agent("temp-1")
        assert engine.get_agent_key("temp-1") is None

    # ── CKKS search ──────────────────────────────────────────

    def test_encrypt_and_search(self, engine):
        # Store two embeddings
        e1 = engine.encrypt_embedding([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        e2 = engine.encrypt_embedding([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        engine.store_embedding("doc-1", e1)
        engine.store_embedding("doc-2", e2)

        # Query similar to doc-1
        query = engine.encrypt_query([0.9, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        results = engine.search_similar(query, top_k=2)

        assert len(results) == 2
        assert results[0].chunk_id == "doc-1"   # higher cosine sim
        assert results[0].similarity > results[1].similarity

    def test_search_respects_candidate_ids(self, engine):
        e1 = engine.encrypt_embedding([1.0] + [0.0] * 7)
        e2 = engine.encrypt_embedding([0.0, 1.0] + [0.0] * 6)
        engine.store_embedding("a", e1)
        engine.store_embedding("b", e2)

        query = engine.encrypt_query([0.0, 1.0] + [0.0] * 6)
        results = engine.search_similar(query, top_k=2, candidate_ids=["b"])
        assert len(results) == 1
        assert results[0].chunk_id == "b"

    def test_search_empty_store(self, engine):
        query = engine.encrypt_query([1.0] * 8)
        results = engine.search_similar(query)
        assert len(results) == 0

    def test_embedding_dimension_mismatch(self, engine):
        with pytest.raises(ValueError):
            engine.encrypt_embedding([1.0, 2.0])   # wrong dim

    def test_stats(self, engine):
        s = engine.stats()
        assert s["registered_agents"] == 0
        assert s["stored_embeddings"] == 0
        assert s["ckks_dimension"] == 8
        assert s["total_decrypts"] == 0

    # ── Decrypt log ─────────────────────────────────────────

    def test_decrypt_log_accumulates(self, engine):
        agent = AgentLabel(agent_id="a1", role=Role.ANALYST,
                           clearance=Clearance.L3_SECRET,
                           trust_intrinsic=Trust.T3_HIGH,
                           task_domain={"t1"}, epoch=1)
        engine.register_agent(agent)
        mem = MemoryLabel(chunk_id="m1", sensitivity=Clearance.L0_PUBLIC,
                          provenance_trust=Trust.T2_MEDIUM, layer=Layer.CONCLUSION,
                          memory_type=MemoryType.INTEL, owner_agent="planner-1",
                          task_binding="t1", epoch=1)
        ct = engine.encrypt_memory("hello", mem)

        engine.decrypt_memory(agent, ct)
        engine.decrypt_memory(agent, ct)
        assert len(engine.decrypt_log) == 2
        assert engine.stats()["total_decrypts"] == 2


# ═══════════════════════════════════════════════════════════
# Integration: CryptoEngine + policy_from_label
# ═══════════════════════════════════════════════════════════

class TestCryptoPolicyIntegration:

    def test_full_policy_encrypt_decrypt(self):
        """End-to-end: policy generated from MemoryLabel, keys from AgentLabel."""
        topo = Topology()
        topo.add_agent("planner-1", parent=None)
        topo.add_agent("analyst-1", parent="planner-1")
        topo.add_agent("executor-1", parent="planner-1")

        engine = CryptoEngine(topo)

        # Register two agents with different attributes
        analyst = AgentLabel(agent_id="analyst-1", role=Role.ANALYST,
                             clearance=Clearance.L2_SENSITIVE,
                             trust_intrinsic=Trust.T2_MEDIUM,
                             task_domain={"incident-42"}, collab_group={"sec"},
                             epoch=1)
        executor = AgentLabel(agent_id="executor-1", role=Role.EXECUTOR,
                              clearance=Clearance.L1_INTERNAL,
                              trust_intrinsic=Trust.T1_LOW,
                              task_domain={"incident-99"}, collab_group={"ops"},
                              epoch=1)
        engine.register_agent(analyst)
        engine.register_agent(executor)

        # Memory created by planner, bound to incident-42
        mem = MemoryLabel(chunk_id="m-sec", sensitivity=Clearance.L2_SENSITIVE,
                          provenance_trust=Trust.T3_HIGH, layer=Layer.CONCLUSION,
                          memory_type=MemoryType.SEMANTIC, owner_agent="planner-1",
                          task_binding="incident-42", collab_group={"sec"},
                          epoch=1)

        ct = engine.encrypt_memory("security finding", mem)

        # Analyst (correct task, correct clearance, correct group) can decrypt
        plain, _ = engine.decrypt_memory(analyst, ct)
        assert plain is not None

        # Executor (wrong task, wrong group) cannot decrypt
        plain, reason = engine.decrypt_memory(executor, ct)
        assert plain is None
        assert "DENY" in reason

    def test_r_layer_restricts_to_ancestors(self):
        """R layer memory should only be decryptable by owner + ancestors + auditor."""
        topo = Topology()
        topo.add_agent("planner-1", parent=None)
        topo.add_agent("analyst-1", parent="planner-1")
        topo.add_agent("retriever-1", parent="planner-1")
        # analyst-2 is under analyst-1, so analyst-1 is its ancestor
        topo.add_agent("analyst-2", parent="analyst-1")

        engine = CryptoEngine(topo)

        planner = AgentLabel(agent_id="planner-1", role=Role.PLANNER,
                             clearance=Clearance.L3_SECRET,
                             trust_intrinsic=Trust.T3_HIGH,
                             task_domain={"task"}, epoch=1)
        # analyst-2: NOT an ancestor of planner-1
        analyst2 = AgentLabel(agent_id="analyst-2", role=Role.ANALYST,
                              clearance=Clearance.L2_SENSITIVE,
                              trust_intrinsic=Trust.T2_MEDIUM,
                              task_domain={"task"}, epoch=1)
        auditor = AgentLabel(agent_id="auditor-1", role=Role.AUDITOR,
                             clearance=Clearance.L3_SECRET,
                             trust_intrinsic=Trust.T3_HIGH,
                             task_domain={"task"}, epoch=1)

        engine.register_agent(planner)
        engine.register_agent(analyst2)
        engine.register_agent(auditor)

        # R-layer memory owned by planner-1
        mem = MemoryLabel(chunk_id="r1", sensitivity=Clearance.L2_SENSITIVE,
                          provenance_trust=Trust.T3_HIGH, layer=Layer.REASONING,
                          memory_type=MemoryType.TRAJECTORY, owner_agent="planner-1",
                          task_binding="task", epoch=1)

        ct = engine.encrypt_memory("planner reasoning chain", mem)

        # Planner (owner) can decrypt R-layer
        assert engine.decrypt_memory(planner, ct)[0] is not None

        # Auditor can decrypt R-layer (bypass)
        assert engine.decrypt_memory(auditor, ct)[0] is not None

        # analyst-2 (not an ancestor of planner-1) cannot decrypt
        plain, reason = engine.decrypt_memory(analyst2, ct)
        assert plain is None
