"""initial_schema

Revision ID: ae451d215883
Revises: 
Create Date: 2026-08-09 14:53:40.053998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae451d215883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('denied_by', sa.String(length=32), nullable=True),
    sa.Column('side_effect', sa.String(length=256), nullable=True),
    sa.Column('checks_detail', sa.JSON(), nullable=True),
    sa.Column('merkle_root', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('sensitivity', sa.Integer(), nullable=False),
    sa.Column('provenance_trust', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=4), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('owner_agent', sa.String(length=32), nullable=False),
    sa.Column('task_binding', sa.String(length=64), nullable=False),
    sa.Column('collab_group', sa.JSON(), nullable=True),
    sa.Column('provenance_chain', sa.JSON(), nullable=True),
    sa.Column('lifecycle', sa.String(length=12), nullable=True),
    sa.Column('epoch', sa.Integer(), nullable=True),
    sa.Column('declassified', sa.Boolean(), nullable=True),
    sa.Column('content_encrypted', sa.Text(), nullable=True),
    sa.Column('ttl_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_chunks_chunk_id'), 'memory_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_memory_chunks_owner_agent'), 'memory_chunks', ['owner_agent'], unique=False)
    op.create_index(op.f('ix_memory_chunks_task_binding'), 'memory_chunks', ['task_binding'], unique=False)
    op.create_table('provenance_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_chunk_id', sa.String(length=64), nullable=False),
    sa.Column('target_chunk_id', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=16), nullable=False),
    sa.Column('op_effective', sa.String(length=16), nullable=False),
    sa.Column('t_inputs', sa.Integer(), nullable=False),
    sa.Column('t_agent', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('trust_out', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenance_links_source_chunk_id'), 'provenance_links', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_provenance_links_target_chunk_id'), 'provenance_links', ['target_chunk_id'], unique=False)
    op.create_table('read_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('t_eff_before', sa.Integer(), nullable=False),
    sa.Column('t_eff_after', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_read_records_chunk_id'), 'read_records', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_read_records_session_id'), 'read_records', ['session_id'], unique=False)
    op.create_table('session_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('t_eff', sa.Integer(), nullable=False),
    sa.Column('t_intrinsic', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('consulted', sa.JSON(), nullable=True),
    sa.Column('hitl_confirmations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_records_agent_id'), 'session_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_session_records_session_id'), 'session_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_records_session_id'), table_name='session_records')
    op.drop_index(op.f('ix_session_records_agent_id'), table_name='session_records')
    op.drop_table('session_records')
    op.drop_index(op.f('ix_read_records_session_id'), table_name='read_records')
    op.drop_index(op.f('ix_read_records_chunk_id'), table_name='read_records')
    op.drop_table('read_records')
    op.drop_index(op.f('ix_provenance_links_target_chunk_id'), table_name='provenance_links')
    op.drop_index(op.f('ix_provenance_links_source_chunk_id'), table_name='provenance_links')
    op.drop_table('provenance_links')
    op.drop_index(op.f('ix_memory_chunks_task_binding'), table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_owner_agent'), table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_chunk_id'), table_name='memory_chunks')
    op.drop_table('memory_chunks')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
